# 日志收集配置块
input:

# 存放各类日志文件的glob匹配路径
- log_path: ["/var/folders/lp/jd6nj9ws5r3br43_y7qw66zw0000gn/T/.nm_logs/nm_apps?/*.log"]
  # 在输入中排除符合正则表达式列表的日志行
  #exclude_lines: ["test"]

  # 包含输入中符合正则表达式列表的日志行
  #include_lines: ["^\\w+"]

  # 忽略掉符合正则表达式列表的文件
  #exclude_files: ["\\d{4}.log"]

  # 默认为false, 从文件开始处重新发送所有内容。设置为true会从文件尾开始监控文件新增内容把新增的每一行文件进行发送
  tail_files: true

  #检测是否有新增日志文件的频率，默认为10秒
  scan_frequency: 10

  # 最后一次读取文件后，持续时间内没有再写入日志，将关闭文件句柄，默认是 5分钟
  #close_inactive: 300

  # 发送自定义字段，默认会放在fields字段下, 当然也可以使用json字符串, 如  '{"a":"b"}'
  #fields: "some field here"

  # 多行匹配
  multiline:
    # 多行匹配点
    pattern: "^normal_log"
    # 最多匹配多少行，默认10
    #max_lines: 10

- log_path: ["/var/folders/lp/jd6nj9ws5r3br43_y7qw66zw0000gn/T/.nm/*.log"]
  # 多行匹配
  multiline:
    # 多行匹配点
    pattern: "^error_log"
    # 最多匹配多少行，默认10
    max_lines: 5
  scan_frequency: 20

# 输出配置块:
output:

  # 把收集到的日志发送到指定API
  # 请求boby中带有JSON数据，以POST方法发送至指定接口
  #api_server:
  # 是否启用
  #enable: false
  #url: "http://127.0.0.1:9200/nma"

  elasticsearch:
    # 是否启用
    enable: false
    host: ["http://127.0.0.1:9200/"]
    index: "nma"
    # 输出认证.
    #username: "admin"
    #password: "s3cr3t"

# 通用配置块

# 应用名
#name: "llog"
# 是否上报系统级别日志（cpu，内存，磁盘，网络）, 默认为false，不上报
#sys_info: true

# 系统信息上报时间间隔，默认为10秒
#sys_info_during: 10

# 设置最大使用cpu数量, 默认无限制
#max_procs: 8

# 文件状态保持配置
#snapshot:
  # 文件状态开关, 默认不开启
  #enable: false

  # 文档状态保存，快照当前状态到本地，下次启动会优先使用快照内容
  #snapshot_dir: '/path/to/snapshot/file'

  # 定时保存文件状态，默认为5秒
  #snapshot_during: 5
